apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: 0.0.0.0
port: 20250
readOnlyPort: 0
serializeImagePulls: false
cgroupDriver: systemd
failSwapOn: false
staticPodPath: /etc/kubernetes/manifests
containerRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
authentication:
  webhook:
    enabled: false
authorization:
  mode: AlwaysAllow
logging:
  verbosity: 5
evictionHard:
    memory.available:  "100Mi"
    nodefs.available:  "10%"
    nodefs.inodesFree: "5%"
    imagefs.available: "15%"
    imagefs.inodesFree: "5%"
