apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "v1.33.4"
imageRepository: registry.k8s.io
networking:
  podSubnet: "192.168.0.0/16"
apiServer:
  certSANs:
    - 127.0.0.1
    - 192.168.70.49
    - 10.96.0.1
    - localhost
controllerManager:
  extraArgs:
    bind-address: "127.0.0.1"
scheduler:
  extraArgs:
    bind-address: "127.0.0.1"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  name: cp-1
  kubeletExtraArgs:
    v: "5"
