apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: "192.168.0.8"
port: 20250
serializeImagePulls: false
cgroupDriver: systemd
failSwapOn: false
podManifestPath: /etc/kubernetes/manifests
containerRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
hostnameOverride: localhost
logging:
  verbosity: 5
evictionHard:
    memory.available:  "100Mi"
    nodefs.available:  "10%"
    nodefs.inodesFree: "5%"
    imagefs.available: "15%"
    imagefs.inodesFree: "5%"
