#cloud-init script to stand up a kubernetes cluster on ubuntu 24.04 LTS

#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

runcmd:
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] \
   https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | \
   sudo tee /etc/apt/sources.list.d/kubernetes.list
  - apt-get update -y
  - apt-get install -y kubelet kubeadm kubectl
  - kubeadm init --pod-network-cidr=10.100.0.0/16
  - mkdir -p /root/.kube
  - cp /etc/kubernetes/admin.conf /root/.kube/config
