#cloud-init script to stand up a kubernetes cluster on ubuntu 24.04 LTS

#cloud-config
package_update: true
package_upgrade: true

#install packages. do not install docker. use containerd.
packages:
  # Base system and Kubernetes prerequisites
  - apt-transport-https           # Enables HTTPS for APT repositories
  - ca-certificates               # Validates SSL certificates
  - curl                          # Fetches binaries and configs
  - gnupg                         # Handles GPG keys for repo signing
  - lsb-release                   # Detects distro info for conditional logic
  - software-properties-common    # Adds external repositories
  - containerd                    # Container runtime (preferred over Docker)
  - socat                         # Required for kube-proxy and port forwarding
  - conntrack                     # Tracks network connections (used by kube-proxy)
  - iptables                      # Ensures firewall compatibility
  - ebtables                      # Handles Ethernet bridging (CNI support)
  - ethtool                       # Diagnoses NIC behavior and link status
  - net-tools                     # Legacy but useful for `ifconfig`, `netstat`
  - neovim                        # For clarity annotation and YAML editing
  - systemd                       # Ensures journalctl and service management

  # Diagnostic and Monitoring Suite
  - htop                          # Interactive process viewer for CPU/memory load
  - lsof                          # Lists open files and ports (bind visibility)
  - strace                        # Syscall-level tracing for container startup failures
  - tcpdump                       # Packet inspection for control plane probes and TLS
  - iftop                         # Real-time network usage by interface
  - nethogs                       # Per-process bandwidth monitoring
  - iproute2                      # Modern IP, SS, TC tools for socket and route inspection
  - nmap                          # Port scanning and service discovery across nodes
  - wget                          # Alternative HTTP probe tool
  - jq                            # JSON parsing for `crictl inspect` and runtime metadata
  - auditd                        # System audit logging for symbolic rupture tracing
  - e2fsprogs                     # Filesystem diagnostics (fsck, tune2fs, etc.)
  - util-linux                    # Includes mount, umount, blkid, and other core tools
  - prometheus-node-exporter     # Exposes system metrics for Prometheus scraping


# Register kubelet as a sytemd service
write_files:
  - path: /home/ubuntu/etc/kubelet-config.yaml
    permissions: '0644'
    content: |
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      address: "192.168.0.8"
      port: 20250
      serializeImagePulls: false
      cgroupDriver: systemd
      failSwapOn: false
      podManifestPath: /etc/kubernetes/manifests
      containerRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
      hostnameOverride: localhost
      logging:
        verbosity: 5
      evictionHard:
        memory.available: "100Mi"
        nodefs.available: "10%"
        nodefs.inodesFree: "5%"
        imagefs.available: "15%"
        imagefs.inodesFree: "5%"

  - path: /etc/systemd/system/kubelet.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Kubelet Service
      Documentation=https://kubernetes.io/docs/
      After=network.target
      logging:
        verbosity: 5
      [Service]
      ExecStart=/usr/bin/kubelet \
        --config=/home/ubuntu/etc/kubelet-config.yaml
      Restart=always
      StartLimitInterval=0
      RestartSec=10

      [Install]
      WantedBy=multi-user.target


runcmd:
  # Update package index
  - sudo apt-get update -y

  # Install Kubernetes binaries (ARM64)
  - curl -LO https://dl.k8s.io/release/v1.33.4/bin/linux/arm64/kubectl
  - curl -LO https://dl.k8s.io/release/v1.33.4/bin/linux/arm64/kubeadm
  - curl -LO https://dl.k8s.io/release/v1.33.4/bin/linux/arm64/kubelet
  - chmod +x kubectl kubeadm kubelet
  - sudo mv kubectl kubeadm kubelet /usr/bin/

  # Install crictl (CRI client)
  - curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.33.0/crictl-v1.33.0-linux-arm64.tar.gz
  - tar -zxvf crictl-v1.33.0-linux-arm64.tar.gz
  - chmod +x crictl
  - sudo mv crictl /usr/local/bin/

  # Configure containerd
  - sudo mkdir -p /etc/containerd
  - sudo containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
  - sudo systemctl enable containerd
  - sudo systemctl restart containerd

  # Initialize bridge traffic inspection (CNI compatibility)
  - modprobe br_netfilter
  - echo 'br_netfilter' | sudo tee -a /etc/modules
  - echo 'net.bridge.bridge-nf-call-iptables=1' | sudo tee /etc/sysctl.d/k8s.conf
  - sudo sysctl --system

  # Enable and start kubelet
    ## Ensure the 'write_files' section is pre-configured
  - sudo mkdir -p /etc/systemd/system/kubelet.service.d
  - sudo systemctl daemon-reexec
  - sudo systemctl daemon-reload
  - sudo systemctl enable kubelet
  - sudo systemctl start kubelet

## TODO: rebooting