#cloud-init script to stand up a kubernetes cluster on ubuntu 24.04 LTS

#cloud-config
package_update: true
package_upgrade: true

#install packages. do not install docker. use containerd.
packages:
  - apt-transport-https     # Enables HTTPS for APT
  - ca-certificates         # Validates SSL certs
  - curl                    # Fetches binaries and configs
  - gnupg                   # Handles GPG keys for repo signing
  - lsb-release             # Detects distro info
  - software-properties-common  # Adds external repos
  - containerd              # Container runtime (preferred over Docker)
  - socat                   # Required for kube-proxy and port forwarding
  - conntrack               # Tracks network connections (used by kube-proxy)
  - iptables                # Ensures firewall compatibility
  - ebtables                # Handles Ethernet bridging (CNI support)
  - ethtool                 # Diagnoses NIC behavior
  - net-tools               # Legacy but useful for `ifconfig`, `netstat`

# Register kubelet as a sytemd service
write_files:
  - path: /etc/systemd/system/kubelet.service
    permissions: '0644'
    content: |
      [Unit]
      Description=Kubelet
      Documentation=https://kubernetes.io/docs/
      After=network.target

      [Service]
      ExecStart=/usr/bin/kubelet
      Restart=always
      StartLimitInterval=0
      RestartSec=10

      [Install]
      WantedBy=multi-user.target


runcmd:
  # Update package index
  - sudo apt-get update -y

  # Install Kubernetes binaries (ARM64)
  - curl -LO https://dl.k8s.io/release/v1.33.4/bin/linux/arm64/kubectl
  - curl -LO https://dl.k8s.io/release/v1.33.4/bin/linux/arm64/kubeadm
  - curl -LO https://dl.k8s.io/release/v1.33.4/bin/linux/arm64/kubelet
  - chmod +x kubectl kubeadm kubelet
  - sudo mv kubectl kubeadm kubelet /usr/bin/

  # Install crictl (CRI client)
  - curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.33.0/crictl-v1.33.0-linux-arm64.tar.gz
  - tar -zxvf crictl-v1.33.0-linux-arm64.tar.gz
  - chmod +x crictl
  - sudo mv crictl /usr/local/bin/

  # Configure containerd
  - sudo mkdir -p /etc/containerd
  - sudo containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
  - sudo systemctl enable containerd
  - sudo systemctl restart containerd

  # Initialize bridge traffic inspection (CNI compatibility)
  - modprobe br_netfilter
  - echo 'br_netfilter' | sudo tee -a /etc/modules
  - echo 'net.bridge.bridge-nf-call-iptables=1' | sudo tee /etc/sysctl.d/k8s.conf
  - sudo sysctl --system

  # Enable and start kubelet
    ## Ensure the 'write_files' section is pre-configured
  - sudo mkdir -p /etc/systemd/system/kubelet.service.d
  - sudo systemctl daemon-reexec
  - sudo systemctl daemon-reload
  - sudo systemctl enable kubelet
  - sudo systemctl start kubelet

## TODO: rebooting