apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-app
  namespace: argocd
spec:
  project: multipass-vms-on-apple-m1
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.9.0
    helm:
      parameters:
        - name: controller.service.type
          value: LoadBalancer
        - name: controller.replicaCount
          value: "3"
        - name: controller.metrics.enabled
          value: "true"
        - name: controller.nodeSelector."node-role\.kubernetes\.io/control-plane"
          value: ""
        - name: controller.tolerations[0].key
          value: "node-role.kubernetes.io/control-plane"
        - name: controller.tolerations[0].operator
          value: "Exists"
        - name: controller.tolerations[0].effect
          value: "NoSchedule"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
