apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: nginx-app
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      port: 8080       # External port on the LB IP
      targetPort: 80   # Internal port in the Pod
